### PR TITLE
Heartbeat

### PR DESCRIPTION
**Pull request by JohanDegraeve**
**Heartbeat with xDrip4iOS**

- option to make bluetooth connection to CGM transmitter, which will then work as heartbeat.
Disabled by default. Can be enabled in xDrip4iOS UI.
A call is made to fetchNewDataIfNeeded each time there's a call to 'peripheral(_:didUpdateValueFor:error:)' or centralManager(_:didDisconnectPeripheral:error:)
The call on didDisconnect is useful for Dexcom users, the call on didUpdateValueFor is for the Libre users

(note for Libre 2 users : the reading will run 1 minute behind)

Steps :
      - If you haven't setup your CGM yet in xDrip4iOS : 
         - Force close Loop
         - in xDrip4iOS make sure you have made a first connection to the CGM
     - force close xDrip4iOS
     - reopen Loop
     - select xDrip4iOS as CGM and open the xDrip4iOS UI
     - enable "use CGM as heartbeat"
     - keep the app in the foreground and wait till the text under the UISwitch changes to "Did connect to CGM. You can now run both xDrip4iOS and Loop". Once you see this text, you can reopen xDrip4iOS

**Other Changes** 

- removed DispatchTimer. Timers don't work when the app is in the background. App will soon be suspended after going to background and timers are triggered. The Bluetooth trigger mechanism is what will wake up the app and trigger a fetch of the last reading

- in xDripClientManager.fetchNewDataIfNeeded :  replaced all
   self.delegateQueue.async { completion( .. data ..) }
     By
   self.delegate.notify { (delegate) in delegate?.cgmManager(self, didUpdateWith: .noData) }
Because in case fetchNewDataIfNeeded due to wake up signal by BluetoothTransmitter, then there's no completion handler available.
Not doing the call asynchronously, this was causing Loop failures

- add observer on UIApplication.didFinishLaunchingNotification and UIApplication.willEnterForegroundNotification : a call to fetchNewDataIfNeeded is made when triggered. This ensures that the most recent reading is fetched when the user brings Loop to the foreground

- enable/disable upload readings by Loop to Remote Service : Loop uses the boolean shouldSyncToRemoteService in CGMManager to determine of upload of glucose readings to remote service (like NightScout). This boolean can now be set to true or false in the xDrip4iOS UI

### CODE REVIEW

**Comment by marionbarker** [comment]
I changed the PR to be a request for freeaps_dev - but the last commit before the PR was created was to merge freeaps into heartbeat.
This was not the right thing to do with git - because we want your heartbeat branch to come into freeaps_dev (not freeaps).
I don't know if you want to start over with a new PR or revert that last commit for this PR.
We can chat about this tomorrow or the next day.

**Comment by JohanDegraeve** [comment]
that will need a chat. I'll first try to understand better what I did
wrong. That will be in 12 hours, (It's 08 AM here)
I'll contact you via Zulip

Op do 9 jun. 2022 om 07:03 schreef Marion Barker ***@***.***>:

**Comment by marionbarker** [comment]
I'm sure you did not mean to change the localization strings.
Let me try doing some testing locally without going through github.
I worry about force pushing anything.

**Comment by marionbarker** [comment]
Let me take a crack at fixing this.  Give me a little while.

**Comment by marionbarker** [comment]
I set up loopnlearn branch called heartbeat_for_merging.
These are the files that I removed or brought over from your heatbeat branch:
```
A       Common/ConstantsxDripClient.swift
D       Common/DispatchTimer.swift
A       Common/Trace.swift
A       Extensions/CBManagerState.swift
A       Extensions/StringProtocol.swift
A       Extensions/URL.swift
A       Extensions/UserDefaults.swift
M       xDripClient.xcodeproj/project.pbxproj
A       xDripClient/BluetoothTransmitter.swift
M       xDripClient/xDripClient.swift
M       xDripClient/xDripClientManager.swift
M       xDripClientUI/xDripClientSettingsViewController.swift
```

I'll set up a new PR. If you can test that this works, I'll close this PR and merge that one. Give me another minute to set up the PR.

**Comment by marionbarker** [comment]
PR #9  is ready for your review.

**Comment by marionbarker** [comment]
Closing this because the desired files have been updated with PR #9

**Pull request closed without merging**
